---
language: node_js
node_js:
  - "8"

sudo: required

services:
  - docker

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - docker run -d -p 9200:9200 --rm cardstack/elasticsearch:dev

install:
  - yarn install

before_script:
  - wget -q --waitretry=1 --retry-connrefused -T 1 -O - http://127.0.0.1:9200

script:
  - yarn test
